# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('JottoWebApp', '0003_auto_20170812_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guess',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
