# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('JottoWebApp', '0004_auto_20170812_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
