# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('JottoWebApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guess',
            old_name='pre_session',
            new_name='session',
        ),
        migrations.AddField(
            model_name='guess',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='guess',
            name='guess',
            field=models.CharField(editable=False, max_length=128),
        ),
    ]
